services:

  app:
    container_name: focuscmsdemo-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
    ports:
      - "90:90"
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - demo-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: focuscmsdemo-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PMA_HOST: focuscmsdemo-db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - demo-net

  mailhog:
    image: mailhog/mailhog
    container_name: focuscmsdemo-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - demo-net

networks:
  demo-net:
    external: true