; php.ini a WordPress és a fejlesztési környezet optimalizálásához

; Memória
memory_limit = 512M
post_max_size = 2048M
upload_max_filesize = 2048M
max_execution_time = 3000
max_input_time = 300
date.timezone = Europe/Budapest

; Hibaüzenetek (fejlesztéshez)
error_reporting = E_ALL & ~E_NOTICE
display_errors = On
display_startup_errors = On
log_errors = Off

; Opcache (Teljesítmény)
; Engedélyezve a Dockerfile-ban a 'opcache' extension telepítésével
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 2
; Állítsa 0-ra produkciós környezetben!a

# Opcache beállítások finomítása a php.ini-ben
opcache.save_comments = 1
opcache.load_comments = 1
