services:
  db:
    image: mariadb:11
    container_name: focuscmsdemo-db
    restart: unless-stopped
    user: "${DEV_UID}:${DEV_GID}"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: focuscmsdemo
      MYSQL_USER: focuscmsdemo
      MYSQL_PASSWORD: focuscmsdemo
    ports:
      - "3306:3306"
    networks:
      - demo-net
    volumes:
      - ./db_data:/var/lib/mysql:Z

networks:
  demo-net:
    external: true