services:
  node:
    user: "${DEV_UID}:${DEV_GID}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
    ports:
      - "5173:5173"
    container_name: focuscmsdemo-nj
    working_dir: /var/www/focuscms
    command: tail -f /dev/null
    volumes:
      - ../webstack/www:/var/www
      - node_modules:/var/www/focuscms/node_modules
    networks:
      - demo-net

networks:
  demo-net:
    external: true

volumes:
  node_modules:
